name: align build

on:
  push:
    paths-ignore:
      # remove non chibios HAL
      - 'libraries/AP_HAL_Linux/**'
      - 'libraries/AP_HAL_ESP32/**'
      - 'libraries/AP_HAL_SITL/**'
      # remove non stm directories
      - 'Tools/CHDK-Script/**'
      - 'Tools/CodeStyle/**'
      - 'Tools/completion/**'
      - 'Tools/debug/**'
      - 'Tools/environment_install/**'
      - 'Tools/FilterTestTool/**'
      - 'Tools/Frame_params/**'
      - 'Tools/geotag/**'
      - 'Tools/GIT_Test/**'
      - 'Tools/gittools/**'
      - 'Tools/Hello/**'
      - 'Tools/LogAnalyzer/**'
      - 'Tools/mavproxy_modules/**'
      - 'Tools/Pozyx/**'
      - 'Tools/PrintVersion.py'
      - 'Tools/Replay/**'
      - 'Tools/simulink/**'
      - 'Tools/UDP_Proxy/**'
      - 'Tools/vagrant/**'
      - 'Tools/Vicon/**'
      # Remove vehicles autotest we need support of test_build_option.py in the Tools/autotest directory
      - 'Tools/autotest/antennatracker.py'
      - 'Tools/autotest/arduplane.py'
      - 'Tools/autotest/ardusub.py'
      - 'Tools/autotest/balancebot.py'
      - 'Tools/autotest/location.txt'
      - 'Tools/autotest/quadplane.py'
      - 'Tools/autotest/rover.py'
      - 'Tools/autotest/sailboat.py'
      - 'Tools/autotest/swarminit.txt'
      # Remove markdown files as irrelevant
      - '**.md'
      # Remove dotfile at root directory
      - './.dir-locals.el'
      - './.dockerignore'
      - './.editorconfig'
      - './.flake8'
      - './.gitattributes'
      - './.github'
      - './.gitignore'
      - './.pre-commit-config.yaml'
      - './.pydevproject'
      - './.valgrind-suppressions'
      - './.valgrindrc'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
      # Remove some directories check
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      # Remove change on other workflows
      - '.github/workflows/test_environment.yml'

  workflow_dispatch:
    paths-ignore:
      # remove non chibios HAL
      - 'libraries/AP_HAL_Linux/**'
      - 'libraries/AP_HAL_ESP32/**'
      - 'libraries/AP_HAL_SITL/**'
      # remove non stm directories
      - 'Tools/CHDK-Script/**'
      - 'Tools/CodeStyle/**'
      - 'Tools/completion/**'
      - 'Tools/debug/**'
      - 'Tools/environment_install/**'
      - 'Tools/FilterTestTool/**'
      - 'Tools/Frame_params/**'
      - 'Tools/geotag/**'
      - 'Tools/GIT_Test/**'
      - 'Tools/gittools/**'
      - 'Tools/Hello/**'
      - 'Tools/LogAnalyzer/**'
      - 'Tools/mavproxy_modules/**'
      - 'Tools/Pozyx/**'
      - 'Tools/PrintVersion.py'
      - 'Tools/Replay/**'
      - 'Tools/simulink/**'
      - 'Tools/UDP_Proxy/**'
      - 'Tools/vagrant/**'
      - 'Tools/Vicon/**'
      # Remove vehicles autotest we need support of test_build_option.py in the Tools/autotest directory
      - 'Tools/autotest/antennatracker.py'
      - 'Tools/autotest/arduplane.py'
      - 'Tools/autotest/ardusub.py'
      - 'Tools/autotest/balancebot.py'
      - 'Tools/autotest/location.txt'
      - 'Tools/autotest/quadplane.py'
      - 'Tools/autotest/rover.py'
      - 'Tools/autotest/sailboat.py'
      - 'Tools/autotest/swarminit.txt'
      # Remove markdown files as irrelevant
      - '**.md'
      # Remove dotfile at root directory
      - './.dir-locals.el'
      - './.dockerignore'
      - './.editorconfig'
      - './.flake8'
      - './.gitattributes'
      - './.github'
      - './.gitignore'
      - './.pre-commit-config.yaml'
      - './.pydevproject'
      - './.valgrind-suppressions'
      - './.valgrindrc'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
      # Remove some directories check
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      # Remove change on other workflows
      - '.github/workflows/test_environment.yml'

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ardupilot/ardupilot-dev-chibios:v0.1.3
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        config: [
            AP3-GA22,
            AP3-GA22-dev,
            AP3-GA45,
            AP3-GA45-dev,
            AP6-GA22,
            AP6-GA22-dev,
            AP6-GA45,
            AP6-GA45-dev,
            AP6v2-GA22,
            AP6v2-GA22-dev,
            AP6v2-GA45,
            AP6v2-GA45-dev,
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: align rover build
        shell: bash
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/usr/lib/ccache:/opt/gcc-arm-none-eabi-10/bin:$PATH"
          PATH="/github/home/.local/bin:$PATH"
          ./waf configure --board ${{matrix.config}}
          ./waf clean
          ./waf rover

      - name: upload rover apj
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config}}
          path: build/${{matrix.config}}/bin/ardurover.apj

  upload:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: create align-build dir
        run: mkdir -p align-build

      - name: download apj
        uses: actions/download-artifact@v3
        with:
          path: align-build

      - name: create ZIP align-build
        run: |
          zip -r align-build/align-build.zip align-build/

      - name: upload ZIP align-build
        uses: actions/upload-artifact@v3
        with:
          name: align-build
          path: align-build/align-build.zip

      - name: cleanup
        if: always()
        run: |
          rm -rf align-build